FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential gcc ffmpeg && rm -rf /var/lib/apt/lists/*

COPY RecommendationService/requirements.txt .

RUN pip install -r requirements.txt 

COPY RecommendationService/ .

EXPOSE 5005

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5005"]